# See http://www.appveyor.com/docs/appveyor-yml for many more options

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: +lqWVtVRayO6KNlJeu9lrnzmtGXreNPIr1Fn3dhXxYTJAHHAOPCPVWvFVkRX7wlr
  GitToken:
    secure: m8fv0iJ0CQHaQsAGgdlOe+M/oI8CcDls9BBG19oeUB3NZEsVCc4px9iZQIIIZSr6

# Allow WMF5 (i.e. PowerShellGallery functionality)
#os: WMF 5

image:
- WMF 5
- Ubuntu
- Visual Studio 2017

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated README.*|update README.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - pwsh: .\test.ps1

for:
-
  matrix:
    only:
      - image: WMF 5
  
  test_script:
  - ps: .\test.ps1

on_success:
- ps: .\deploy.ps1
- cmd: git config --global credential.helper store
- ps: if (git status -s) { Add-Content "$HOME/.git-credentials" "https://$($env:GitToken):x-oauth-basic@github.com`n" }
- cmd: |
    git config --global user.email "build@appveyor.com"
    git config --global user.name "Appveyor"
    git checkout %APPVEYOR_REPO_BRANCH%
    git add *.psd1
    git add *.md
    git commit -m "[skip ci] AppVeyor Build %APPVEYOR_BUILD_VERSION%"
    git push